name: Snowflake OIDC Authentication

on:
  workflow_dispatch:   # run manually for testing
  push:                # optional - run on pushes to main
    branches:
      - main

jobs:
  snowflake-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for OIDC
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install snowflake-connector-python jq

      - name: Request GitHub OIDC Token
        id: idtoken
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=snowflakecomputing.com" | jq -r .value)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Run Python Script
        run: |
          python connect_snowflake.py \
            --account "sfcsupport-anshul_prod_west" \
            --token "${{ steps.idtoken.outputs.token }}"
